name: CI Runner

on:
  workflow_dispatch:

# 赋予自动触发工作流的权限
permissions:
  actions: write
  contents: read

jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - name: Start Environment
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --advertise-exit-node --hostname=gh-node

      - name: Setup Network
        run: |
          sudo sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1
          sudo sysctl -w net.ipv4.conf.all.rp_filter=2 > /dev/null 2>&1
          sudo sysctl -w net.ipv4.conf.default.rp_filter=2 > /dev/null 2>&1
          IFACE=$(ip route show default | awk '{print $5}')
          sudo iptables -t nat -A POSTROUTING -o "$IFACE" -j MASQUERADE
          sudo iptables -I FORWARD 1 -j ACCEPT

      - name: Auto-Relay Keep Alive
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 挂起运行 5 小时（留足安全缓冲，绝不触碰 6 小时硬顶）
          sleep 18000
          
          # 显式指定仓库名 -R TFORMYYYX/mm，无 .git 目录下依然能成功触发续杯
          gh workflow run x.yml -R TFORMYYYX/mm || true
          
          # 双机重叠保持 5 分钟，等待新节点上线交接
          sleep 300
