name: CI Runner

on:
  workflow_dispatch:

# 赋予自动触发工作流的权限
permissions:
  actions: write
  contents: read

jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - name: Start Environment
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --advertise-exit-node --hostname=gh-node

      - name: Setup Network
        run: |
          sudo sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1
          sudo sysctl -w net.ipv4.conf.all.rp_filter=2 > /dev/null 2>&1
          sudo sysctl -w net.ipv4.conf.default.rp_filter=2 > /dev/null 2>&1
          IFACE=$(ip route show default | awk '{print $5}')
          sudo iptables -t nat -A POSTROUTING -o "$IFACE" -j MASQUERADE
          sudo iptables -I FORWARD 1 -j ACCEPT

      - name: Auto-Relay Keep Alive
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 挂起运行 5 小时 50 分钟（提前 10 分钟准备交接）
          sleep 21000
          
          # 自动触发启动下一个任务（实现无缝自动续杯）
          gh workflow run x.yml || true
          
          # 跑满最后 10 分钟然后平稳关机
          sleep 600
